services:
  # redis:
  #   image: valkey/valkey:7.2-alpine # this doesn ot have JSON support built in currently :-(
  #   restart: unless-stopped
  #   command: valkey-server --port ${AWSAPPENV_DOCKER_REDIS_PORT} --requirepass ${AWSAPPENV_DOCKER_REDIS_PASS} --appendonly yes --save 120 1 --loglevel warning
  #   #ports:
  #   # - "${AWSAPPENV_DOCKER_REDIS_PORT}:${AWSAPPENV_DOCKER_REDIS_PORT}"
  #   environment:
  #     - TZ=UTC
  #   networks:
  #     - appnetwork
  #   volumes:
  #     - ${AWSAPPENV_DOCKER_LOCALMOUNTPATH_REDIS}:/data
  #   healthcheck:
  #     test: [ "CMD-SHELL", "valkey-cli -a ${AWSAPPENV_DOCKER_REDIS_PASS} -p ${AWSAPPENV_DOCKER_REDIS_PORT} ping | grep PONG"]
  #     interval: 3600s
  #     timeout: 10s
  #     retries: 3
  #     start_interval: 15s
  #     start_period: 15s

  redis:
    image: redis/redis-stack:7.2.0-v11 #for prod: redis-stack-server -> no redis-insight included
    restart: unless-stopped
    #command: redis-server --port ${AWSAPPENV_DOCKER_REDIS_PORT} --requirepass ${AWSAPPENV_DOCKER_REDIS_PASS} --appendonly yes --save 120 1 --loglevel warning --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    ports:
     - "${AWSAPPENV_DOCKER_REDIS_PORT}:${AWSAPPENV_DOCKER_REDIS_PORT}"
     - 8001:8001
    environment:
      - TZ=UTC
    networks:
      - appnetwork
    volumes:
      - ${AWSAPPENV_DOCKER_LOCALMOUNTPATH_REDIS}:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${AWSAPPENV_DOCKER_REDIS_PASS} -p ${AWSAPPENV_DOCKER_REDIS_PORT} ping | grep PONG"]
      interval: 3600s
      timeout: 10s
      retries: 3
      start_interval: 15s
      start_period: 15s

  nuxt:
    depends_on:
      - redis
    restart: unless-stopped
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: nuxt_run
    environment:
      - TZ=UTC
    networks:
      - appnetwork
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://$(hostname):${AWSAPPENV_DOCKER_APP_CONTAINERPORT}/healthcheck').then(res => res.ok)\""]
      interval: 3600s
      timeout: 10s
      retries: 3
      start_interval: 15s
      start_period: 15s



networks:
  appnetwork:
    driver: bridge